/* the Strings resource class 
 * Here the strings resources are generated by apktool and the corresponding file locates at
 * ".../res/values/strings.xml"
 * */
public class ResStrings{
	private String name; /* "name" */
	private String content;
	
	/* constructor */
	public ResStrings(String name, String content){
		this.name = name;
		this.content = content;
	}
	/* getter */
	public String getName(){
		return this.name;
	}
	public String getContent(){
		return this.content;
	}
	/* toString */
	public String toString(){
		return this.name + "  " + this.content;
	}
}